version: '3'
services: 
  mongodb:
    image: 'mongo:4.0'
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: 'json-file'
      options:
        max-size: "1M"
        max-file: "1"